services:
  aperture:
    image: akhilmulpuri/aperture-web:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DEFAULT_SERVER_URL=${NEXT_PUBLIC_DEFAULT_SERVER_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
